Add tutorial notebooks
lnls-fac/collective_effects pull request #22
Opened 2024-05-23 20:15 UTC by fernandohds564

2024-05-29 18:23 UTC, xresende approved these changes

2024-06-13 20:45 UTC, murilobalves requested changes

2024-06-13 20:45 UTC, murilobalves commented on pycolleff/examples/tutorial_mulilayer_resistive_wall.ipynb
typo in notebook name: mulilayer

2024-06-14 20:19 UTC, fernandohds564 commented on pycolleff/examples/tutorial_mulilayer_resistive_wall.ipynb
fixed. thanks!

2024-06-17 12:28 UTC, murilobalves approved these changes

2024-06-17 12:55 UTC, merged