ssh update
lnls-fac/collective_effects pull request #4
Opened 2022-03-07 16:59 UTC by iagocarvalhoa

If .ssh folder does not exist, ssh-keygen will create it and then this command must be executed first

2022-03-07 17:30 UTC, fernandohds564 requested changes

2022-03-07 17:30 UTC, fernandohds564 commented on collective_effects_installation_tutorial.txt
>  - ssh-keygen
I think you should add a condition here. In case the key already exists, it is not necessary (not desirable, actually) to create it again.

2022-03-09 20:34 UTC, fernandohds564 approved these changes

2022-03-09 20:46 UTC, murilobalves approved these changes

2022-03-10 11:19 UTC, merged